# Generated by Django 3.1.8 on 2022-11-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20221106_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='firstpresent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='secondpresent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
